# WRITTEN BY Shadow Hacker 99 AND MANAGED BY The Wizard 99

name: Shadow Ripping Tools

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste CRD's 2nd Code
        required: true

jobs:
  build:
    name: Shadow Ripping Lab Running
    runs-on: windows-latest

    steps:
    - name: Downloading And Installing Tools
      run: |
        # WAIT FOR 3-4 MINUTES 
        Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=1IWdNFHaewULn7tN8ZOnp3fMfsSSuCxOU&export=download&authuser=0&confirm=t&uuid=fdbceb6f-1b4d-49c1-9128-d38cf855055b&at=APZUnTVUm1AGqItiY6LCUoXfH13d%3A1716612457921" -OutFile "ripper.ps1" && ./ripper.ps1
    - name: Starting VirtualMachine 
      run: |
        # CONNECTING WITH VIRTUAL MACHINE
        ${{ inputs }} -pin=123456
    - name: VirtualMachine is Running
      run: |
        $i = 360
         do {
             Write-Host $i
             Sleep 60
             $i--
        } while ($i -gt 0)
